name: Bump up versin
description: Bump up versin
title: "[Bump up]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Issue for Bump up version
  - type: dropdown
    id: version_up_target
    attributes:
      label: Version up target
      description: 
      options:
        - build_number
        - patch_version
        - minor_version
        - major_version
      default: 1
    validations:
      required: true
